/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionSelectModal: typeof import('./src/components/menu/ActionSelectModal.vue')['default']
    AiChat: typeof import('./src/components/AiChat.vue')['default']
    AiTaskMenu: typeof import('./src/components/menu/AiTaskMenu.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatItem: typeof import('./src/components/common/ChatItem.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/ChatSidebar.vue')['default']
    ContentPadding: typeof import('./src/components/common/ContentPadding.vue')['default']
    CorrectionMenu: typeof import('./src/components/menu/CorrectionMenu.vue')['default']
    Diff: typeof import('./src/components/common/Diff.vue')['default']
    DiffInput: typeof import('./src/components/common/DiffInput.vue')['default']
    DiffMenu: typeof import('./src/components/menu/DiffMenu.vue')['default']
    DropdownMenu: typeof import('./src/components/common/DropdownMenu.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditorContextMenu: typeof import('./src/components/editor/EditorContextMenu.vue')['default']
    EditorInput: typeof import('./src/components/EditorInput.vue')['default']
    FieldCheckbox: typeof import('./src/components/common/FieldCheckbox.vue')['default']
    FieldInput: typeof import('./src/components/common/FieldInput.vue')['default']
    FieldItems: typeof import('./src/components/common/FieldItems.vue')['default']
    FieldRow: typeof import('./src/components/common/FieldRow.vue')['default']
    FieldsByCfg: typeof import('./src/components/common/FieldsByCfg.vue')['default']
    FieldSelect: typeof import('./src/components/common/FieldSelect.vue')['default']
    FieldTextArea: typeof import('./src/components/common/FieldTextArea.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    InProgressMessage: typeof import('./src/components/menu/InProgressMessage.vue')['default']
    InsertMenu: typeof import('./src/components/menu/InsertMenu.vue')['default']
    KeyButton: typeof import('./src/components/common/KeyButton.vue')['default']
    MenuModals: typeof import('./src/components/menu/MenuModals.vue')['default']
    NavPanel: typeof import('./src/components/NavPanel.vue')['default']
    Overlay: typeof import('./src/components/common/Overlay.vue')['default']
    PreviewMenu: typeof import('./src/components/menu/PreviewMenu.vue')['default']
    QuickOverlay: typeof import('./src/components/quick/QuickOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/common/SearchInput.vue')['default']
    SegmentedControl: typeof import('./src/components/common/SegmentedControl.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SettingsHotkeysTab: typeof import('./src/components/settings/SettingsHotkeysTab.vue')['default']
    SettingsLlmTab: typeof import('./src/components/settings/SettingsLlmTab.vue')['default']
    SettingsMainActionsTab: typeof import('./src/components/settings/SettingsMainActionsTab.vue')['default']
    SettingsPluginsTab: typeof import('./src/components/settings/SettingsPluginsTab.vue')['default']
    SettingsRulesTab: typeof import('./src/components/settings/SettingsRulesTab.vue')['default']
    SettingsSection: typeof import('./src/components/common/SettingsSection.vue')['default']
    SettingsTasksTab: typeof import('./src/components/settings/SettingsTasksTab.vue')['default']
    SettingsTranslationsTab: typeof import('./src/components/settings/SettingsTranslationsTab.vue')['default']
    ShortcutButton: typeof import('./src/components/common/ShortcutButton.vue')['default']
    ShortcutList: typeof import('./src/components/ShortcutList.vue')['default']
    ShortcutSlots: typeof import('./src/components/common/ShortcutSlots.vue')['default']
    TabItem: typeof import('./src/components/common/TabItem.vue')['default']
    Tabs: typeof import('./src/components/common/Tabs.vue')['default']
    TextPreview: typeof import('./src/components/common/TextPreview.vue')['default']
    TranslateMenu: typeof import('./src/components/menu/TranslateMenu.vue')['default']
    VoiceRecognitionMenu: typeof import('./src/components/menu/VoiceRecognitionMenu.vue')['default']
    WindowTitlebar: typeof import('./src/components/WindowTitlebar.vue')['default']
    WriteModeInput: typeof import('./src/components/WriteModeInput.vue')['default']
  }
}
